### ISSUE TITLE
Errors when trying to import as NPM module ("TypeError: Cannot read property 'x' of undefined")

### ISSUE THREAD

**Issue by jurb** [jurb/vue2-leaflet-heatmap#1]
I'm getting lots of `"TypeError: Cannot read property 'x' of undefined"` errors when trying to import this as an npm module in my project. When I copy the `Vue2LeafletHeatmap.vue` to my components and import it, everything works as expected.

Errors:

![screen shot 2018-08-30 at 15 16 44](https://user-images.githubusercontent.com/913411/44854187-33c62500-ac68-11e8-91dc-a606e5ed9013.png)

Desired result with heatmap, by using `Vue2LeafletHeatmap.vue` directly:

![screen shot 2018-08-30 at 15 19 58](https://user-images.githubusercontent.com/913411/44854220-46d8f500-ac68-11e8-8fc0-039c73c690b2.png)

**Comment by jperelli** [comment]
this is probably because in some place you are not initializing some variable, then you need a `v-if` directive somewhere, like, instead of this:
```
<LCircle latlng="latlngpoint" />
```
(if latlngpoint happens to be undefined, you would get the error you reported)
try this:
```
<LCircle v-if="latlngpoint" latlng="latlngpoint" />
```

**Comment by jurb** [comment]
@jperelli Thank you, but I'm still puzzled about how to go about solving this. All my variables are declared, and the component works if I include it as a .vue file in my project. If I import it as a built file via npm, I get these error messages. Adding a `v-if` does not work.

**Comment by nmezzopera** [comment]
@jurb I will try to take a look a this in the coming days!

**Comment by jurb** [comment]
@lordfuoco Awesome, let me know if I can help!

**Comment by nparley** [comment]
I have had issues with leaflet being isolated when using different versions between vue2leaflet and an app with webpack. This does not look like the problem here though because the package.lock looks ok with matching `1.3.4`. But you could always experiment by removing the requires leaflet from vue2leaflet in the lock file before building to see if that helps.

**Comment by jurb** [comment]
Thanks to the great work of @lordfuoco we have a functioning npm package now, with working examples. When I include it into my own project however, I get the same `[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'x' of undefined"` error again. It seems to be something to do with the order of vue2-leaflet components, and my own component.

When I use the .vue component directly in my project instead of importing the npm module it all works out. If someone comes across the same issue and knows how to solve it I'm all ears.

**Comment by nmezzopera** [comment]
@jurb @nparley yes is what nparley is saying, please look at this issue that I made for more details
https://github.com/KoRiGaN/Vue2Leaflet/issues/281

**Comment by unre4l** [comment]
Hi, any news on this particular topic?

**Comment by jurb** [comment]
@lordfuoco Thanks, since I'm rather new at this, how would I go about removing leaflet as a peerdependency for this plugin? I added it as a peerDependency to my package.json, but I still get the same error when using it in my app via npm. Do I need to use a certain version?

**Comment by nparley** [comment]
Hi @jurb have you tired changing:

```
import L from "leaflet";
import "leaflet.heat";
import { findRealParent, propsBinder } from "vue2-leaflet";
```
to
```
import { findRealParent, propsBinder, L } from "vue2-leaflet";
import "leaflet.heat";
```

this will mean that the heat map plugin is added to the leaflet version that vue2leaflet is using. You might not need leaflet as a dependency at all after that.

**Comment by jurb** [comment]
@nparley Thanks for the suggestion, but no, it doesn't help.

**Comment by nparley** [comment]
Your latest version works for me when running the examples, I did have to change 
`"vue2-leaflet-heatmap": "file:../vue2-leaflet-heatmap-1.0.5.tgz"` so it picked up the correct version. 
![image](https://user-images.githubusercontent.com/6215361/48983220-e846da00-f0e3-11e8-984d-f7f1a7d13d98.png)

**Comment by jericopulvera** [comment]
I'm having this issue as well. On latest version of both package. Vue2Leaflet and vue2-leaflet-heatmap.

**Comment by slawinski** [comment]
Hi. I'm experiencing the same issue. Was this solved and there's something wrong on my side or is it still work-in-progress? I think I have tried everything mentioned in this issue thread as well as in related threads and it's always `TypeError: Cannot read property 'x' of undefined`. I have the latest versions of `leaflet`, `vue2-leaflet` and `vue2-leaflet-heatmap`. 
Thanks in advance!

**Comment by nmezzopera** [comment]
@slawinski did you try to alias `leaflet` in your webapck / nuxt config?

**Comment by slawinski** [comment]
@DonNicoJs apparently I tried everything besides that. The below in `vue.config.js` did the trick. Thanks a bunch!
```
const path = require('path');

module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        leaflet: path.join(__dirname, 'node_modules/leaflet'),
      },
    },
  },
};
```

**Comment by vicentecastroa** [comment]
Had the same issue and the solution above worked fine! @slawinski

**Comment by ciarans** [comment]
This issue has not been resolved. The package does not work out of the box. Don't waste your time using it.

**Comment by jurb** [comment]
I removed the package from NPM because I can't fix this and other errors. Using the `Vue2LeafletHeatmap.vue` directly works. If someone wants to have a go at turning it into a working npm package, be my guest!

**Comment by ciarans** [comment]
```
Failed to compile.

./src/components/VueHeatmap.vue
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/user/IdeaProjects/apps/app/src/components/VueHeatmap.vue
  75:30  error  'L' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
````

Calling directly fails.

**Comment by ciarans** [comment]
adding  ``` const L = window.L;``` 

````
 import { findRealParent, propsBinder } from "vue2-leaflet";
    import { DomEvent } from "leaflet";
    import "leaflet.heat";
    const L = window.L;
````

Fixes it. Seems hacky but passes lint tests.

**Comment by jurb** [comment]
@ciarans Thanks, added your suggestion https://github.com/jurb/vue2-leaflet-heatmap/commit/f389194905258d37c2c38a6854d2e909006541d0

**Comment by ciarans** [comment]
thanks @jurb
