### ISSUE TITLE
How to use it with nuxt?

### ISSUE THREAD

**Issue by sowinski** [jurb/vue2-leaflet-heatmap#11]
Hi,

how can I use this plugin with nuxt?

Can someone show an example?

Thank you!

**Comment by ndemasie** [comment]
@sowinski

Here is a sample of how I got it working in a nuxt app.
I'm not sure why using the package directly breaks but what I did is...

Copy [Vue2LeafletHeatmap.vue](https://github.com/jurb/vue2-leaflet-heatmap/blob/master/Vue2LeafletHeatmap.vue) into a component file like `@/components/base/LHeatmap.vue`

Create a client plugin like
```
// plugins/leaflet.client.ts
import Vue from 'vue'
import { LMap, LTileLayer, LGeoJson } from 'vue2-leaflet'
import LHeatmap from '@/components/base/LHeatmap.vue'

Vue.component('LMap', LMap)
Vue.component('LTileLayer', LTileLayer)
Vue.component('LGeoJson', LGeoJson)
Vue.component('LHeatmap', LHeatmap)
```

Add plugin to `nuxt.config.js`
```
  plugins: [
    ...
    '~/plugins/leaflet.client.ts', // client only 
  ],
```

Use in component
```
// components/base/BaseMap.vue
<template>
    <client-only>
      <LMap>
        <LHeatmap ... />
      </LMap>
    </client-only>
</template>
```

**Comment by jurb** [comment]
Unfortunately, I cannot get the component to work as an npm module. My advice would be to manually copy the .vue file in this repo into your project, like @ndemasie did above, that seems to work.
