### ISSUE TITLE
Error in callback for watcher "latLng": "TypeError: e[r] is not a function"

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [jurb/vue2-leaflet-heatmap#2]
Any idea why this error could be coming?

**Comment by jurb** [comment]
@ankitsinghaniyaz Sorry for the late reply, just figured this out: I mispelled the lat-lng prop in the readme. If you use `lat-lng`, you should be good!

**Comment by jersobh** [comment]
I'm getting this error also 
```
vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in callback for watcher "latLng": "TypeError: e[r] is not a function"

found in

---> <LHeatmap> at Vue2LeafletHeatmap.vue
       <LMap>
         <QPage>
           <PageIndex> at src/pages/Index.vue
             <QPageContainer>
               <QLayout>
                 <MyLayout> at src/layouts/MyLayout.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?2b0e:587
logError @ vue.runtime.esm.js?2b0e:1733
globalHandleError @ vue.runtime.esm.js?2b0e:1728
handleError @ vue.runtime.esm.js?2b0e:1717
run @ vue.runtime.esm.js?2b0e:3231
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
Promise.then (async)
microTimerFunc @ vue.runtime.esm.js?2b0e:1802
nextTick @ vue.runtime.esm.js?2b0e:1846
queueWatcher @ vue.runtime.esm.js?2b0e:3064
update @ vue.runtime.esm.js?2b0e:3205
notify @ vue.runtime.esm.js?2b0e:693
reactiveSetter @ vue.runtime.esm.js?2b0e:1010
proxySetter @ vue.runtime.esm.js?2b0e:3296
registerLocation @ Index.vue?b484:248
vue.runtime.esm.js?2b0e:1737 TypeError: e[r] is not a function
    at VueComponent.n.(:8080/anonymous function).custom.setOptions.t.$watch.deep (webpack-internal:///./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:1495)
    at Watcher.run (vue.runtime.esm.js?2b0e:3229)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:2977)
    at Array.eval (vue.runtime.esm.js?2b0e:1833)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1754)
```

heatmap array: 
```
heatmap:Array[5]
0:Object
lat:-19.9204777
lng:-43.920882899999995
1:Object
lat:-19.9204777
lng:-43.920882899999995
2:Object
lat:-19.9204777
lng:-43.920882899999995
3:Object
lat:-19.9204777
lng:-43.920882899999995
4:Object
lat:-19.9204777
lng:-43.920882899999995
```

**Comment by evgencode** [comment]
The same error.
Error appears when I try to dynamically add point to the heatmap.
Code example (used from example):
```
<template>
    <div class="basic-example">
        <l-map style="height: 100%; overflow: auto;" :zoom="10" :center="[56.31603, 43.990642]" ref="map">
            <l-tile-layer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></l-tile-layer>
            <Vue2LeafletHeatmap :lat-lng="latlngs" :radius="60" :min-opacity=".75" :max-zoom="18" :blur="60"></Vue2LeafletHeatmap>
        </l-map>
    </div>
</template>
<script>
    import { LMap, LTileLayer } from "vue2-leaflet";
    import Vue2LeafletHeatmap from "vue2-leaflet-heatmap";
    export default {
        components: {
            LMap,
            LTileLayer,
            Vue2LeafletHeatmap
        },
        data() {
            return {
                latlngs: []
            };
        },
        mounted() {
            if(this.$refs.map) {
                this.$refs.map.mapObject.on('click', ({ latlng: { lat, lng }}) => {
                    this.latlngs.push([lat, lng]);
                })
            }
        }
    };
</script>
<style>
    .basic-example {
        width: 100%;
        height: 500px;
    }
</style>
```

**Comment by prasadKodeInCloud** [comment]
This error still exists when ever changing the latlngs array dynamically. why is this issue marked as closed? 

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "latLng": "TypeError: e[r] is not a function"

found in

---> <LHeatmap> at Vue2LeafletHeatmap.vue
       <LMap>
         <GsMap>
           <Drop>
             <Panel> at src/components/common/Panel.vue
               <Map> at src/views/Map.vue
                 <MainLayout> at src/views/MainLayout.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1874
globalHandleError @ vue.runtime.esm.js?2b0e:1869
handleError @ vue.runtime.esm.js?2b0e:1835
run @ vue.runtime.esm.js?2b0e:4510
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4250
(anonymous) @ vue.runtime.esm.js?2b0e:1970
flushCallbacks @ vue.runtime.esm.js?2b0e:1896
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1923
nextTick @ vue.runtime.esm.js?2b0e:1980
queueWatcher @ vue.runtime.esm.js?2b0e:4342
update @ vue.runtime.esm.js?2b0e:4484
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4571
onClearDocuments @ Map.vue?108f:354
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1847
invoker @ vue.runtime.esm.js?2b0e:2169
original._wrapper @ vue.runtime.esm.js?2b0e:6855
vue.runtime.esm.js?2b0e:1878 TypeError: e[r] is not a function
    at VueComponent.n.(:8080/anonymous function).custom.t.$watch.deep (webpack-internal:///./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:1495)
    at Watcher.run (vue.runtime.esm.js?2b0e:4508)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4250)
    at Array.eval (vue.runtime.esm.js?2b0e:1970)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1896)

**Comment by prasadKodeInCloud** [comment]
@jurb By adding following watch to manually reset the latlngs array, I was able to reset heatmap view for new latlngs. But still getting the console error. 

watch:{
   latLng( newVal ){
       this.mapObject.setLatLngs( this.latLng )     
    }
  }

**Comment by jurb** [comment]
@prasadKodeInCloud the issue was closed because I never came across the bug with dynamically added latlngs. The issue was opened for another reason and fixed by using a proper prop name.

Just because you see the same error message in the console doesn't mean that the issue is the same.

I'll open a new issue for your problem.

I don't see any way to fix this myself for the time being.

**Comment by prasadKodeInCloud** [comment]
Thanks! 😄

**Comment by sowinski** [comment]
Got this error using nuxt.

```
e[r] is not a function
An error occurred while rendering the page. Check developer tools console for details.
```

```
ypeError: Cannot read property 'x' of undefined
    at Bounds.contains (leaflet-src.js?e207:1037)
    at NewClass._redraw (leaflet-heat.js?a662:11)
    at NewClass._reset (leaflet-heat.js?a662:11)
    at NewClass.onAdd (leaflet-heat.js?a662:11)
    at NewClass._layerAdd (leaflet-src.js?e207:6487)
    at NewClass.whenReady (leaflet-src.js?e11e:4477)
    at NewClass.addLayer (leaflet-src.js?e11e:6679)
    at VueComponent.addLayer (LMap.js?2699:357)
    at VueComponent.mounted (Vue2LeafletHeatmap.common.js?87b9:261)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
```
Any idea?

I defined the latlngs in my data
```
data() {
    return {
      latlnglocation: [47.334852, -1.509485],
      loaded: false,
      startdate: new Date().setFullYear(new Date().getFullYear(), 0, 1),
      enddate: new Date(),
      latlngs: [
        [47.334852, -1.509485, 1],
        [47.342596, -1.328731, 0.75],
        [47.342596, -1.329731, 1],
        [47.342596, -1.329731, 1],
        [47.342596, -1.329731, 1],
        [47.241487, -1.190568, 0.5],
        [47.234787, -1.358337, 1]
      ]
    }
  },``

**Comment by sowinski** [comment]
https://github.com/jurb/vue2-leaflet-heatmap/issues/10
Solved it here.

Did someone of you manage to add or delete points dynamically?
