### ISSUE TITLE
 Error in callback for watcher "latLng" when dynamically adding lat-lng points

### ISSUE THREAD

**Issue by jurb** [jurb/vue2-leaflet-heatmap#7]
Apparently dynamically adding latlng points throws a 
`Error in callback for watcher "latLng": "TypeError: e[r] is not a function"` error, see #2.

I can't get this repo to run on my computer currently and don't see any time to fix it soon, so cheers to anyone who can pick this up.

**Comment by Qubeo** [comment]
Hi, any progress on this? Would love to use the plugin, but can't seem to figure this out...

**Comment by sowinski** [comment]
Same problem here. Any idea?

**Comment by MonrealRyan** [comment]
maybe this will help, I use `addLatLng()` method of this package:

```
...
<Vue2LeafletHeatmap
          ref="heatmap"
          :lat-lng="latLangs"
          :radius="10"
          :min-opacity=".75"
          :max-zoom="10"
          :blur="10"/>
...
```

In script add this code:
```
this.$refs.heatmap.addLatLng([lat, lng, count]);
```

cheers!!

**Comment by jurb** [comment]
Fixed via https://github.com/jurb/vue2-leaflet-heatmap/pull/15
